#library "global"
#include "zcommon.acs"

script 999 ENTER
{
  int levelnum = GetLevelInfo(LEVELINFO_LEVELNUM);

	if (levelnum > 0 && levelnum < 666)  { FadeRange(255, 255, 255, 1.0, 0, 0, 0, 0.0, 1.0); }
    if (levelnum == 1)   { HudMessage(s:"\cjYou better start save-scumming now\n\cjif you thought the Tag Labs was infuriating...\n\cjI mean if you want to, I dunno I haven't gotten any sleep.\n                       \cm- \cbunRyker";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 2)   { HudMessage(s:"\cjDon't worry, ma'am.\n\cjI study memes as a profession.\n\cjYour virginity is in good hands.\n                       \cm- \cbAnonymous";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 3)   { HudMessage(s:"\cjI WANT TO SHOOT THE AGITATION WITH AGITATION AHHHHHHH!\n                       \cm- \cbdemo_the_man";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 4)   { HudMessage(s:"\cjYou better play this keyboard only!\n                       \cm- \cbGardevoir";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 5)   { HudMessage(s:"\cjParticipating in this was a lot of fun!\n\cjI was glad to be a part of it.\n                       \cm- \cbCJacobs";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 6)   { HudMessage(s:"\cjWow, that's a lot of red textures\n                       \cm- \cbVBob";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 7)   { HudMessage(s:"\cjThis map is 512x512 and oh man,\n\cjI don't think you could go any smaller\n\cjand still have a playable map.\n                       \cm- \cbHoodoo456";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 8)   { HudMessage(s:"\cjIf you don't like how your map is going,\n\cjtake the best part(s) and start over\n                       \cm- \cbTitan314";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 9)   { HudMessage(s:"\cjBecause of the extension,\n\cjnow I actually have to fix my map.\n                       \cm- \cbProject_ILE";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 10)  { HudMessage(s:"\cjWait, why are my doors only opening from one side?\n                       \cm- \cbSpudTheRubbish";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 11)  { HudMessage(s:"\cjJust remember to take your boots off\n\cjbefore stepping onto the castle!\n                       \cm- \cbBeed28";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 12)  { HudMessage(s:"\cjNo Man's Dump.\n                       \cm- \cbcombatxtreme";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 13)  { HudMessage(s:"\cjThe Fun Lab is where the demons\n\cjmanufacture all of the fun.\n                       \cm- \cbTerminusEst13";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 14)  { HudMessage(s:"\cjMap-making is long and hard,\n\cjjust like the end of this map ;)\n                       \cm- \cbMinimum Payne";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 15)  { HudMessage(s:"\cjLet's try using more than\n\cjone texture, okay...?\n                       \cm- \cbKinsie";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 16)  { HudMessage(s:"\cjSomehow worse than a drunk snapmap session.\n                       \cm- \cbDukka";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 17)  { HudMessage(s:"\cjMaking a map has a steep but short learning \n\cjcurve at first, but once you learn the basics you can go \n\cjin all sorts of directions.\n                       \cm- \cbDukka";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 18)  { HudMessage(s:"\cjKeeping a check list of the fiddly bits and doing them asap\n\cjis probably a good idea if you don't want to find\n\cjyou forgot to test something important.\n                       \cm- \cbDukka";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 19)  { HudMessage(s:"\cjOK\n                       \cm- \cbHumansAmongUs";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 20)  { HudMessage(s:"\cjYay!\n                       \cm- \cbKarolineDianne";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 21)  { HudMessage(s:"\cjMy first Doom map in over 13 years!\n                       \cm- \cbcharcola";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 22)  { HudMessage(s:"\cjguess where I took a break from mapping\n                       \cm- \cbBobBarker";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 23)  { HudMessage(s:"\cjimp impipe impost\n                       \cm- \cbToooooasty";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 24)  { HudMessage(s:"\cjI would of had a Weapon to go with this,\n\cjbut then again Procrastination is my room mate.\n                       \cm- \cbLance Charleson";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 25)  { HudMessage(s:"\cjCan you guess what game\n\cjI was playing when I was working on this?\n                       \cm- \cbSgt. Shivers";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 26)  { HudMessage(s:"\cjgone through three designs and its done\n                       \cm- \cbsimpletonnn";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 27)  { HudMessage(s:"\cjI'll make a sexy doom map just for you termyboi.\n                       \cm- \cbLuigi2600";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 28)  { HudMessage(s:"\cjTricks and traps await you in this sandy tomb...\n                       \cm- \cbAction Max";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 29)  { HudMessage(s:"\cjThe Dark Souls of Doom maps.\n                       \cm- \cbAbyssWalker";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 30)  { HudMessage(s:"\cj97% of software renderers HATE this map!\n\cjClick HERE to find out about this one simple trick!\n                       \cm- \cbdeathz0r";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 31)  { HudMessage(s:"\cjI don't like this map, but at least it exists\n                       \cm- \cbArchXeno";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 32)  { HudMessage(s:"\cjIf i had a penny for each map i finished...\n\cjI'd still be poor.\n                       \cm- \cbSpiritOfDecay";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 33)  { HudMessage(s:"\cjIn the name of all that's unholy, JUMP!\n\cjJump over platforms, into and out of buildings, and onto enemies' heads.\n                       \cm- \cbSoundofDoomDoors";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 34)  { HudMessage(s:"\cjIf a lazy shit like me can map or code,\nthen you can do it.\n                       \cm- \cbSMG_Marine";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 35)  { HudMessage(s:"\cjRemember, press the big big button\n\cjto defeat the Sempiternal Archvile!\n                       \cm- \cbDarsycho";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 36)  { HudMessage(s:"\cjWhelp, there went my mapping virginity.\n\cjNow with (much less) monsters, too!\n                       \cm- \cbStale_Meat";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 37)  { HudMessage(s:"\cjthe map originally was intended to be something new\n\cjActually a map for Black Warrior, but then it turned out to be\n\cja remake of Dead Simple for lack of time.\n                       \cm- \cbRoxas";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 38)  { HudMessage(s:"\cjthis map was originally going to feature a 'core'\n\cjthat was a giant sksnake pillar the core was called your dick\n\cjso when you hit the fake exit switch you'd get a message like\n\cj'OH NO! YOU DICKS IS BEING INVADED BY THE DEMONS'\n                       \cm- \cbArctangent";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 39)  { HudMessage(s:"\cjAn abandoned nuclear disposal plant has\n\cjbeen overrun by demons. Go deep into the\n\cjfacility to uncover its secrets and escape!\n                       \cm- \cbTotalInjury";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 40)  { HudMessage(s:"\cjAlso known as 'Pluvial Terrace'.\n                       \cm- \cbJimmy";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 41)  { HudMessage(s:"\cjYes, the lava is flowing upwards.\n\cjDon't ask me how, it just is.\n                       \cm- \cbIdiotBitz";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 42)  { HudMessage(s:"\cjThat's us, and we rule!\n                       \cm- \cbStale_Meat";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 43)  { HudMessage(s:"\cjI'm not really a paragon of time management.\n                       \cm- \cbicept";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 44)  { HudMessage(s:"\cjHere's the dilemma.\n\cjI'm fairly drunk\n\cjand want some fucking eggs.\n\cjWhat do?\n                       \cm- \cbAnonymous";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 45)  { HudMessage(s:"\cjShh.\n                       \cm- \cbfloatRand";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 46)  { HudMessage(s:"\cjthe name correlates to it's development\n                       \cm- \cbcomet1338";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 47)  { HudMessage(s:"\cjHaven't do a map for like 9 years, it took\n\cjme a while to re-learn how to use Doom builder 2 .\n                       \cm- \cbwillykuo";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 48)  { HudMessage(s:"\cjFirst map, first time using Doom Builder and SLADE.\n\cjThe level was fun to make, I hope it's fun to play.\n                       \cm- \cbNAG";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 49)  { HudMessage(s:"\cjI'm learning that massing monsters doesn't\n\cjtend to always be the best thing.\n\cjNeed to work on encounters more.\n                       \cm- \cbInsanityBringer";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 50)  { HudMessage(s:"\cjSANDCASTLES ';,,;'/\n                       \cm- \cbPinchySkree";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    // 51 isn't a map.
    if (levelnum == 52)  { HudMessage(s:"\cjHe's going to go cry himself in his wee little pillah!\n                       \cm- \cbZachBrowder";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 53)  { HudMessage(s:"\cjMapping is both easier and harder than you think it is\n                       \cm- \cbVennobennu";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 54)  { HudMessage(s:"\cji like how #zdoom is talking about srb2\n\cjwhile #srb2fun is talking about doom\n                       \cm- \cbTehRealSalt";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 55)  { HudMessage(s:"\cjToo much 3D sectors, demons and water. 7/10.\n                       \cm- \cbleodoom85";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 56)  { HudMessage(s:"\cjThese walls seem Paper Thin...\n                       \cm- \cbProtester";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 57)  { HudMessage(s:"\cjThis isn't rocket science.\n                       \cm- \cbfloatRand";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 58)  { HudMessage(s:"\cjIf truly free be stopped\nnever through all that's happening.\n                       \cm- \cbAnonymous";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 59)  { HudMessage(s:"\cjNever made a doom map before,\n\cjand I just started making lines until I got this.\n\cjI like to think the building is actually owned\n\cjby Time Warner Cable, explaining the demons\n                       \cm- \cbFlipy";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 60)  { HudMessage(s:"\cjWHY DID YOU DO THAT?!\n                       \cm- \cbGhastly";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 61)  { HudMessage(s:"\cjStart small, end big\n                       \cm- \cbFlotilla";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 62)  { HudMessage(s:"\cjDon't forget to unpeg your lower door textures!\n                       \cm- \cbCharlieTheGnarly";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 63)  { HudMessage(s:"\cjCreative idea or lazy design? You decide!\n                       \cm- \cbUntitled";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 64)  { HudMessage(s:"\cjI dare you restart the level on\n\cjUltra Violence. Also mapping is fun, and\n\cjmade better when you learn by doing!\n                       \cm- \cbChrisR91";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 65)  { HudMessage(s:"\cjEngaging Electronic Hell in 3, 2, 1...\n                       \cm- \cbfloatRand";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 66)  { HudMessage(s:"\cjTBH, I chose the music because my\n\cjgirlfriend's favorite game is R&C and I wanted to\n\cjsweeten the deal when she played co-op with me.\n                       \cm- \cbeverennui";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 67)  { HudMessage(s:"\cjThis is the first map I've ever actually\n\cjcompleted for anything, and I just sort of\n\cjwinged it, so I hope it's at least tolerable.\n\cjAlso I'm shit at naming things.\n                       \cm- \cbCheeki";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 68)  { HudMessage(s:"\cjWhat a terrible night for a curse...\n                       \cm- \cbWivicer";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 69)  { HudMessage(s:"\cjYou ever have one of those days\n\cjwhere you just can't see in color anymore?\n                       \cm- \cbTemin_Dump";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    // Map70's quote is already handled in-game
    if (levelnum == 71)  { HudMessage(s:"\cjI didn't actually say this.\n\cjTechnically, this is libel.\n                       \cm- \cbGageat";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 72)  { HudMessage(s:"\cjI don't know I'm making this up as I go.\n                       \cm- \cbLogicalFallacy";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 73)  { HudMessage(s:"\cjCopy paste function is fun.\n\cjAnd makes stuff so much easier.\n\cjAlso, crates.\n                       \cm- \cbmumblemumble";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }

    if (levelnum == 100) { HudMessage(s:"\cjUnspecified quote.\n                       \cm- \cbUnspecified author";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5);  }
    if (levelnum == 101) { HudMessage(s:"\cjmade within an hour.\n                       \cm- \cbDudeDesigns";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5);  }
    if (levelnum == 102) { HudMessage(s:"\cjBasically a claustrophobic introductory map, meant to replace MAP01.\n\cjAnd a big step into learning how to make maps for me.\n                       \cm- \cbMJ79";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5);  }
    if (levelnum == 103) { HudMessage(s:"\cjCheating would be the loser's way out.\n                       \cm- \cbTerminusEst13";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 104) { HudMessage(s:"\cji did a favor for everybody and maked the map07 for dump\n                       \cm- \cbRedead-ITA";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 105) { HudMessage(s:"\cjI bet the UAC did this.\n                       \cm- \cbAnonymous";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }
    if (levelnum == 106) { HudMessage(s:"\cjif you get the endlevel code working, just credit yourself here\n                       \cm- \cbDeviluke Roy";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5); }

	if (levelnum == 666) { FadeRange(255, 0, 0, 1.0, 0, 0, 0, 0.0, 1.0); }
    if (levelnum == 666) { HudMessage(s:"\cjBetter late than never.\n                       \cm- \cbTerminusEst13";HUDMSG_TYPEON | HUDMSG_LOG,1423,CR_UNTRANSLATED,0.1,0.75,5.00,0.05,0.5);  }
}